flyway.locations=filesystem:database/migrations
flyway.table=flyway_schema_history
flyway.validateMigrationNaming=true
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.cleanDisabled=true
flyway.failOnMissingLocations=true
