CREATE TABLE rol (
    codigo_rol VARCHAR2(20 CHAR) NOT NULL,
    nombre VARCHAR2(60 CHAR) NOT NULL,
    CONSTRAINT pk_rol PRIMARY KEY (codigo_rol),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre),
    CONSTRAINT ck_rol_codigo CHECK (
        codigo_rol IN (
            'ADMINISTRADOR',
            'RECEPCIONISTA',
            'MECANICO',
            'INVENTARIO',
            'CLIENTE'
        )
    )
);

CREATE TABLE cliente (
    id_cliente NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(200 CHAR) NOT NULL,
    telefono VARCHAR2(30 CHAR),
    email VARCHAR2(254 CHAR),
    direccion VARCHAR2(500 CHAR),
    nit VARCHAR2(30 CHAR),
    activo NUMBER(1,0) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0) NOT NULL,
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_por NUMBER(18,0) NOT NULL,
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT ck_cliente_activo CHECK (activo IN (0, 1)),
    CONSTRAINT ck_cliente_version CHECK (version_fila > 0),
    CONSTRAINT ck_cliente_fechas CHECK (actualizado_en >= creado_en)
);

CREATE TABLE usuario (
    id_usuario NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_actor VARCHAR2(10 CHAR) NOT NULL,
    id_cliente NUMBER(18,0),
    login_normalizado VARCHAR2(150 CHAR) NOT NULL,
    nombre_mostrado VARCHAR2(200 CHAR) NOT NULL,
    credencial_hash VARCHAR2(1000 CHAR) NOT NULL,
    version_credencial NUMBER(10,0) NOT NULL,
    activo NUMBER(1,0) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0),
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_por NUMBER(18,0),
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_cliente UNIQUE (id_cliente),
    CONSTRAINT uq_usuario_login UNIQUE (login_normalizado),
    CONSTRAINT ck_usuario_tipo CHECK (tipo_actor IN ('INTERNO', 'CLIENTE')),
    CONSTRAINT ck_usuario_variante CHECK (
        (tipo_actor = 'CLIENTE' AND id_cliente IS NOT NULL)
        OR (tipo_actor = 'INTERNO' AND id_cliente IS NULL)
    ),
    CONSTRAINT ck_usuario_version_cred CHECK (version_credencial > 0),
    CONSTRAINT ck_usuario_activo CHECK (activo IN (0, 1)),
    CONSTRAINT ck_usuario_version CHECK (version_fila > 0),
    CONSTRAINT ck_usuario_fechas CHECK (actualizado_en >= creado_en)
);

CREATE TABLE usuario_rol (
    id_usuario_rol NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER(18,0) NOT NULL,
    codigo_rol VARCHAR2(20 CHAR) NOT NULL,
    asignado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    asignado_por NUMBER(18,0) NOT NULL,
    retirado_en TIMESTAMP(6) WITH TIME ZONE,
    retirado_por NUMBER(18,0),
    motivo_retiro VARCHAR2(500 CHAR),
    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario_rol),
    CONSTRAINT ck_usuario_rol_retiro CHECK (
        (retirado_en IS NULL AND retirado_por IS NULL AND motivo_retiro IS NULL)
        OR
        (retirado_en IS NOT NULL AND retirado_por IS NOT NULL AND motivo_retiro IS NOT NULL)
    ),
    CONSTRAINT ck_usuario_rol_fechas CHECK (
        retirado_en IS NULL OR retirado_en >= asignado_en
    )
);

CREATE TABLE sesion (
    id_sesion NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario NUMBER(18,0) NOT NULL,
    identificador_publico RAW(16) NOT NULL,
    creada_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expira_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revocada_en TIMESTAMP(6) WITH TIME ZONE,
    motivo_revocacion VARCHAR2(300 CHAR),
    version_credencial NUMBER(10,0) NOT NULL,
    dispositivo VARCHAR2(150 CHAR),
    CONSTRAINT pk_sesion PRIMARY KEY (id_sesion),
    CONSTRAINT uq_sesion_publica UNIQUE (identificador_publico),
    CONSTRAINT uq_sesion_usuario UNIQUE (id_sesion, id_usuario),
    CONSTRAINT ck_sesion_expiracion CHECK (expira_en > creada_en),
    CONSTRAINT ck_sesion_revocacion CHECK (
        (revocada_en IS NULL AND motivo_revocacion IS NULL)
        OR (revocada_en IS NOT NULL AND motivo_revocacion IS NOT NULL)
    ),
    CONSTRAINT ck_sesion_revocada_en CHECK (
        revocada_en IS NULL OR revocada_en >= creada_en
    ),
    CONSTRAINT ck_sesion_version CHECK (version_credencial > 0)
);

CREATE TABLE token_acceso (
    id_token NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo VARCHAR2(15 CHAR) NOT NULL,
    id_cliente NUMBER(18,0),
    id_usuario NUMBER(18,0),
    id_sesion NUMBER(18,0),
    token_hash RAW(32) NOT NULL,
    emitido_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expira_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    usado_en TIMESTAMP(6) WITH TIME ZONE,
    revocado_en TIMESTAMP(6) WITH TIME ZONE,
    id_predecesor NUMBER(18,0),
    canal_verificado VARCHAR2(15 CHAR),
    destino_verificado VARCHAR2(254 CHAR),
    verificado_en TIMESTAMP(6) WITH TIME ZONE,
    emitido_por NUMBER(18,0),
    CONSTRAINT pk_token_acceso PRIMARY KEY (id_token),
    CONSTRAINT uq_token_hash UNIQUE (token_hash),
    CONSTRAINT uq_token_predecesor UNIQUE (id_predecesor),
    CONSTRAINT ck_token_tipo CHECK (
        tipo IN ('ACTIVACION', 'RECUPERACION', 'RENOVACION')
    ),
    CONSTRAINT ck_token_expiracion CHECK (expira_en > emitido_en),
    CONSTRAINT ck_token_uso CHECK (usado_en IS NULL OR usado_en >= emitido_en),
    CONSTRAINT ck_token_revocacion CHECK (
        revocado_en IS NULL OR revocado_en >= emitido_en
    ),
    CONSTRAINT ck_token_variante CHECK (
        (tipo = 'ACTIVACION'
            AND id_cliente IS NOT NULL
            AND id_usuario IS NULL
            AND id_sesion IS NULL
            AND id_predecesor IS NULL)
        OR
        (tipo = 'RECUPERACION'
            AND id_cliente IS NULL
            AND id_usuario IS NOT NULL
            AND id_sesion IS NULL
            AND id_predecesor IS NULL)
        OR
        (tipo = 'RENOVACION'
            AND id_cliente IS NULL
            AND id_usuario IS NOT NULL
            AND id_sesion IS NOT NULL)
    ),
    CONSTRAINT ck_token_evidencia CHECK (
        (
            canal_verificado IS NULL
            AND destino_verificado IS NULL
            AND verificado_en IS NULL
        )
        OR
        (
            tipo IN ('ACTIVACION', 'RECUPERACION')
            AND canal_verificado IS NOT NULL
            AND destino_verificado IS NOT NULL
            AND verificado_en IS NOT NULL
        )
    ),
    CONSTRAINT ck_token_consumo_verificado CHECK (
        usado_en IS NULL
        OR tipo = 'RENOVACION'
        OR verificado_en IS NOT NULL
    )
);

CREATE TABLE comando (
    id_comando NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ambito VARCHAR2(150 CHAR) NOT NULL,
    clave_idempotencia VARCHAR2(100 CHAR) NOT NULL,
    solicitud_hash RAW(32) NOT NULL,
    tipo_operacion VARCHAR2(60 CHAR) NOT NULL,
    id_actor NUMBER(18,0),
    id_sesion NUMBER(18,0),
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    resultado_codigo NUMBER(3,0) NOT NULL,
    resultado_minimo CLOB,
    CONSTRAINT pk_comando PRIMARY KEY (id_comando),
    CONSTRAINT uq_comando_intencion UNIQUE (ambito, clave_idempotencia),
    CONSTRAINT ck_comando_sesion_actor CHECK (
        id_sesion IS NULL OR id_actor IS NOT NULL
    ),
    CONSTRAINT ck_comando_resultado CHECK (
        resultado_codigo BETWEEN 100 AND 599
    ),
    CONSTRAINT ck_comando_resultado_json CHECK (
        resultado_minimo IS JSON
    )
);

CREATE TABLE auditoria_evento (
    id_auditoria NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_actor NUMBER(18,0),
    id_sesion NUMBER(18,0),
    id_comando NUMBER(18,0),
    ocurrido_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    accion VARCHAR2(80 CHAR) NOT NULL,
    tipo_recurso VARCHAR2(60 CHAR) NOT NULL,
    identificador_recurso VARCHAR2(100 CHAR) NOT NULL,
    motivo VARCHAR2(2000 CHAR) NOT NULL,
    cambios CLOB,
    correlacion VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT pk_auditoria_evento PRIMARY KEY (id_auditoria),
    CONSTRAINT ck_auditoria_sesion_actor CHECK (
        id_sesion IS NULL OR id_actor IS NOT NULL
    ),
    CONSTRAINT ck_auditoria_cambios_json CHECK (cambios IS JSON)
);

CREATE TABLE config_taller (
    id_config NUMBER(1,0) NOT NULL,
    nombre VARCHAR2(150 CHAR) NOT NULL,
    moneda VARCHAR2(3 CHAR) NOT NULL,
    zona_horaria VARCHAR2(60 CHAR) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0),
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_por NUMBER(18,0),
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_config_taller PRIMARY KEY (id_config),
    CONSTRAINT ck_config_taller_singleton CHECK (id_config = 1),
    CONSTRAINT ck_config_taller_moneda CHECK (moneda = 'GTQ'),
    CONSTRAINT ck_config_taller_zona CHECK (
        zona_horaria = 'America/Guatemala'
    ),
    CONSTRAINT ck_config_taller_version CHECK (version_fila > 0),
    CONSTRAINT ck_config_taller_fechas CHECK (actualizado_en >= creado_en)
);
