CREATE TABLE tipo_vehiculo (
    codigo_tipo VARCHAR2(20 CHAR) NOT NULL,
    nombre VARCHAR2(60 CHAR) NOT NULL,
    activo NUMBER(1,0) NOT NULL,
    CONSTRAINT pk_tipo_vehiculo PRIMARY KEY (codigo_tipo),
    CONSTRAINT uq_tipo_vehiculo_nombre UNIQUE (nombre),
    CONSTRAINT ck_tipo_vehiculo_activo CHECK (activo IN (0, 1))
);

CREATE TABLE vehiculo (
    id_vehiculo NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_tipo VARCHAR2(20 CHAR) NOT NULL,
    placa VARCHAR2(20 CHAR),
    vin VARCHAR2(40 CHAR),
    marca VARCHAR2(80 CHAR) NOT NULL,
    modelo VARCHAR2(80 CHAR) NOT NULL,
    anio NUMBER(4,0),
    color VARCHAR2(50 CHAR),
    activo NUMBER(1,0) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0) NOT NULL,
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_por NUMBER(18,0) NOT NULL,
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_vehiculo PRIMARY KEY (id_vehiculo),
    CONSTRAINT uq_vehiculo_placa UNIQUE (placa),
    CONSTRAINT uq_vehiculo_vin UNIQUE (vin),
    CONSTRAINT ck_vehiculo_anio CHECK (anio IS NULL OR anio BETWEEN 1 AND 9999),
    CONSTRAINT ck_vehiculo_activo CHECK (activo IN (0, 1)),
    CONSTRAINT ck_vehiculo_version CHECK (version_fila > 0),
    CONSTRAINT ck_vehiculo_fechas CHECK (actualizado_en >= creado_en)
);

CREATE TABLE propiedad_vehiculo (
    id_propiedad NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_vehiculo NUMBER(18,0) NOT NULL,
    id_cliente NUMBER(18,0) NOT NULL,
    desde_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    hasta_en TIMESTAMP(6) WITH TIME ZONE,
    motivo VARCHAR2(1000 CHAR) NOT NULL,
    registrado_por NUMBER(18,0) NOT NULL,
    cerrado_por NUMBER(18,0),
    id_predecesora NUMBER(18,0),
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_propiedad_vehiculo PRIMARY KEY (id_propiedad),
    CONSTRAINT uq_prop_predecesora UNIQUE (id_predecesora),
    CONSTRAINT uq_prop_contexto UNIQUE (id_propiedad, id_vehiculo, id_cliente),
    CONSTRAINT uq_prop_vehiculo UNIQUE (id_propiedad, id_vehiculo),
    CONSTRAINT ck_propiedad_periodo CHECK (hasta_en IS NULL OR hasta_en > desde_en),
    CONSTRAINT ck_propiedad_cierre CHECK (
        (hasta_en IS NULL AND cerrado_por IS NULL)
        OR (hasta_en IS NOT NULL AND cerrado_por IS NOT NULL)
    )
);

CREATE TABLE qr_token (
    id_qr NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_vehiculo NUMBER(18,0) NOT NULL,
    token_hash RAW(32) NOT NULL,
    emitido_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    emitido_por NUMBER(18,0) NOT NULL,
    expira_en TIMESTAMP(6) WITH TIME ZONE,
    revocado_en TIMESTAMP(6) WITH TIME ZONE,
    revocado_por NUMBER(18,0),
    motivo_revocacion VARCHAR2(500 CHAR),
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_qr_token PRIMARY KEY (id_qr),
    CONSTRAINT uq_qr_token_hash UNIQUE (token_hash),
    CONSTRAINT uq_qr_contexto UNIQUE (id_qr, id_vehiculo),
    CONSTRAINT ck_qr_expiracion CHECK (expira_en IS NULL OR expira_en > emitido_en),
    CONSTRAINT ck_qr_revocado_en CHECK (revocado_en IS NULL OR revocado_en >= emitido_en),
    CONSTRAINT ck_qr_revocacion CHECK (
        (revocado_en IS NULL AND revocado_por IS NULL AND motivo_revocacion IS NULL)
        OR
        (revocado_en IS NOT NULL AND revocado_por IS NOT NULL AND motivo_revocacion IS NOT NULL)
    )
);
