CREATE TABLE cita (
    id_cita NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_vehiculo NUMBER(18,0) NOT NULL,
    origen VARCHAR2(10 CHAR) NOT NULL,
    id_usuario_solicita NUMBER(18,0),
    id_qr_origen NUMBER(18,0),
    nombre_solicitante VARCHAR2(200 CHAR) NOT NULL,
    contacto_solicitante VARCHAR2(254 CHAR) NOT NULL,
    motivo VARCHAR2(1500 CHAR) NOT NULL,
    solicitada_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    inicio_solicitado TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    inicio_programado TIMESTAMP(6) WITH TIME ZONE,
    fin_programado TIMESTAMP(6) WITH TIME ZONE,
    estado VARCHAR2(15 CHAR) NOT NULL,
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_cita PRIMARY KEY (id_cita),
    CONSTRAINT uq_cita_contexto UNIQUE (id_cita, id_vehiculo),
    CONSTRAINT ck_cita_origen CHECK (origen IN ('CUENTA', 'QR', 'PERSONAL')),
    CONSTRAINT ck_cita_variante CHECK (
        (origen = 'CUENTA' AND id_usuario_solicita IS NOT NULL AND id_qr_origen IS NULL)
        OR (origen = 'QR' AND id_usuario_solicita IS NULL AND id_qr_origen IS NOT NULL)
        OR (origen = 'PERSONAL' AND id_usuario_solicita IS NULL AND id_qr_origen IS NULL)
    ),
    CONSTRAINT ck_cita_estado CHECK (
        estado IN ('SOLICITADA', 'CONFIRMADA', 'ATENDIDA', 'CANCELADA', 'NO_ASISTIO')
    ),
    CONSTRAINT ck_cita_horario CHECK (
        (inicio_programado IS NULL AND fin_programado IS NULL)
        OR (inicio_programado IS NOT NULL AND fin_programado IS NOT NULL AND fin_programado > inicio_programado)
    ),
    CONSTRAINT ck_cita_estado_horario CHECK (
        (estado = 'SOLICITADA' AND inicio_programado IS NULL AND fin_programado IS NULL)
        OR (estado IN ('CONFIRMADA', 'ATENDIDA', 'NO_ASISTIO') AND inicio_programado IS NOT NULL AND fin_programado IS NOT NULL)
        OR estado = 'CANCELADA'
    ),
    CONSTRAINT ck_cita_version CHECK (version_fila > 0)
);

CREATE TABLE cita_evento (
    id_evento_cita NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cita NUMBER(18,0) NOT NULL,
    tipo VARCHAR2(20 CHAR) NOT NULL,
    estado_anterior VARCHAR2(15 CHAR),
    estado_nuevo VARCHAR2(15 CHAR) NOT NULL,
    inicio_anterior TIMESTAMP(6) WITH TIME ZONE,
    fin_anterior TIMESTAMP(6) WITH TIME ZONE,
    inicio_nuevo TIMESTAMP(6) WITH TIME ZONE,
    fin_nuevo TIMESTAMP(6) WITH TIME ZONE,
    motivo VARCHAR2(1000 CHAR) NOT NULL,
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_por NUMBER(18,0),
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_cita_evento PRIMARY KEY (id_evento_cita),
    CONSTRAINT ck_cita_evento_tipo CHECK (tipo IN ('SOLICITUD', 'ESTADO', 'REPROGRAMACION')),
    CONSTRAINT ck_cita_evento_est_ant CHECK (
        estado_anterior IS NULL OR estado_anterior IN ('SOLICITADA', 'CONFIRMADA', 'ATENDIDA', 'CANCELADA', 'NO_ASISTIO')
    ),
    CONSTRAINT ck_cita_evento_est_nuevo CHECK (
        estado_nuevo IN ('SOLICITADA', 'CONFIRMADA', 'ATENDIDA', 'CANCELADA', 'NO_ASISTIO')
    ),
    CONSTRAINT ck_cita_evento_semantica CHECK (
        (tipo = 'SOLICITUD'
            AND estado_anterior IS NULL AND estado_nuevo = 'SOLICITADA'
            AND inicio_anterior IS NULL AND fin_anterior IS NULL
            AND inicio_nuevo IS NOT NULL AND fin_nuevo IS NULL)
        OR
        (tipo = 'ESTADO' AND (
            (estado_anterior = 'SOLICITADA' AND estado_nuevo = 'CONFIRMADA'
                AND inicio_anterior IS NULL AND fin_anterior IS NULL
                AND inicio_nuevo IS NOT NULL AND fin_nuevo IS NOT NULL AND fin_nuevo > inicio_nuevo)
            OR
            (estado_anterior = 'SOLICITADA' AND estado_nuevo = 'CANCELADA'
                AND inicio_anterior IS NULL AND fin_anterior IS NULL
                AND inicio_nuevo IS NULL AND fin_nuevo IS NULL)
            OR
            (estado_anterior = 'CONFIRMADA' AND estado_nuevo IN ('ATENDIDA', 'CANCELADA', 'NO_ASISTIO')
                AND inicio_anterior IS NULL AND fin_anterior IS NULL
                AND inicio_nuevo IS NULL AND fin_nuevo IS NULL)
        ))
        OR
        (tipo = 'REPROGRAMACION' AND estado_anterior = estado_nuevo AND (
            (estado_nuevo = 'SOLICITADA'
                AND inicio_anterior IS NOT NULL AND fin_anterior IS NULL
                AND inicio_nuevo IS NOT NULL AND fin_nuevo IS NULL)
            OR
            (estado_nuevo = 'CONFIRMADA'
                AND inicio_anterior IS NOT NULL AND fin_anterior IS NOT NULL AND fin_anterior > inicio_anterior
                AND inicio_nuevo IS NOT NULL AND fin_nuevo IS NOT NULL AND fin_nuevo > inicio_nuevo)
        ))
    ),
    CONSTRAINT ck_cita_evento_actor CHECK (
        registrado_por IS NOT NULL OR tipo = 'SOLICITUD'
    )
);

CREATE TABLE orden_trabajo (
    id_orden NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_vehiculo NUMBER(18,0) NOT NULL,
    id_propiedad_apertura NUMBER(18,0) NOT NULL,
    id_cliente NUMBER(18,0) NOT NULL,
    id_cita NUMBER(18,0),
    proposito VARCHAR2(15 CHAR) NOT NULL,
    ingresado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    kilometraje_ingreso NUMBER(10,1) NOT NULL,
    motivo_ingreso VARCHAR2(2000 CHAR) NOT NULL,
    danos_visibles VARCHAR2(2000 CHAR) NOT NULL,
    estado VARCHAR2(40 CHAR) NOT NULL,
    motivo_cierre VARCHAR2(40 CHAR),
    listo_en TIMESTAMP(6) WITH TIME ZONE,
    entregado_en TIMESTAMP(6) WITH TIME ZONE,
    kilometraje_entrega NUMBER(10,1),
    entregado_a VARCHAR2(200 CHAR),
    entregado_por NUMBER(18,0),
    version_fila NUMBER(10,0) NOT NULL,
    creado_por NUMBER(18,0) NOT NULL,
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_orden_trabajo PRIMARY KEY (id_orden),
    CONSTRAINT uq_orden_cita UNIQUE (id_cita),
    CONSTRAINT ck_orden_proposito CHECK (proposito IN ('COMERCIAL', 'GARANTIA')),
    CONSTRAINT ck_orden_estado CHECK (estado IN (
        'RECIBIDO', 'EN_DIAGNOSTICO', 'ESPERANDO_AUTORIZACION',
        'EN_REPARACION', 'LISTO_PARA_ENTREGA',
        'PENDIENTE_ENTREGA_SIN_REPARACION', 'ENTREGADO',
        'ENTREGADO_SIN_REPARACION', 'CANCELADO'
    )),
    CONSTRAINT ck_orden_km_ingreso CHECK (kilometraje_ingreso >= 0),
    CONSTRAINT ck_orden_km_entrega CHECK (kilometraje_entrega IS NULL OR kilometraje_entrega >= 0),
    CONSTRAINT ck_orden_version CHECK (version_fila > 0),
    CONSTRAINT ck_orden_entrega CHECK (
        (estado IN ('ENTREGADO', 'ENTREGADO_SIN_REPARACION')
            AND entregado_en IS NOT NULL AND kilometraje_entrega IS NOT NULL
            AND entregado_a IS NOT NULL AND entregado_por IS NOT NULL)
        OR
        (estado NOT IN ('ENTREGADO', 'ENTREGADO_SIN_REPARACION')
            AND entregado_en IS NULL AND kilometraje_entrega IS NULL
            AND entregado_a IS NULL AND entregado_por IS NULL)
    )
);

CREATE TABLE orden_evento (
    id_evento_orden NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_orden NUMBER(18,0) NOT NULL,
    tipo VARCHAR2(30 CHAR) NOT NULL,
    estado_anterior VARCHAR2(40 CHAR),
    estado_nuevo VARCHAR2(40 CHAR),
    motivo VARCHAR2(2000 CHAR) NOT NULL,
    detalle CLOB,
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_por NUMBER(18,0) NOT NULL,
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_orden_evento PRIMARY KEY (id_evento_orden),
    CONSTRAINT ck_orden_evento_tipo CHECK (
        tipo IN ('APERTURA', 'ESTADO', 'DETENCION', 'CORRECCION_RECEPCION', 'ENTREGA', 'CANCELACION')
    ),
    CONSTRAINT ck_orden_evento_est_ant CHECK (
        estado_anterior IS NULL OR estado_anterior IN (
            'RECIBIDO', 'EN_DIAGNOSTICO', 'ESPERANDO_AUTORIZACION',
            'EN_REPARACION', 'LISTO_PARA_ENTREGA',
            'PENDIENTE_ENTREGA_SIN_REPARACION', 'ENTREGADO',
            'ENTREGADO_SIN_REPARACION', 'CANCELADO'
        )
    ),
    CONSTRAINT ck_orden_evento_est_nuevo CHECK (
        estado_nuevo IS NULL OR estado_nuevo IN (
            'RECIBIDO', 'EN_DIAGNOSTICO', 'ESPERANDO_AUTORIZACION',
            'EN_REPARACION', 'LISTO_PARA_ENTREGA',
            'PENDIENTE_ENTREGA_SIN_REPARACION', 'ENTREGADO',
            'ENTREGADO_SIN_REPARACION', 'CANCELADO'
        )
    ),
    CONSTRAINT ck_orden_evento_apertura CHECK (
        tipo <> 'APERTURA' OR (estado_anterior IS NULL AND estado_nuevo = 'RECIBIDO')
    ),
    CONSTRAINT ck_orden_evento_estado CHECK (
        tipo <> 'ESTADO' OR (estado_anterior IS NOT NULL AND estado_nuevo IS NOT NULL AND estado_anterior <> estado_nuevo)
    )
);

CREATE TABLE orden_mecanico (
    id_participacion NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_orden NUMBER(18,0) NOT NULL,
    id_mecanico NUMBER(18,0) NOT NULL,
    asignado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    asignado_por NUMBER(18,0) NOT NULL,
    retirado_en TIMESTAMP(6) WITH TIME ZONE,
    retirado_por NUMBER(18,0),
    motivo_retiro VARCHAR2(500 CHAR),
    CONSTRAINT pk_orden_mecanico PRIMARY KEY (id_participacion),
    CONSTRAINT ck_orden_mecanico_retiro CHECK (
        (retirado_en IS NULL AND retirado_por IS NULL AND motivo_retiro IS NULL)
        OR (retirado_en IS NOT NULL AND retirado_por IS NOT NULL AND motivo_retiro IS NOT NULL)
    ),
    CONSTRAINT ck_orden_mecanico_fechas CHECK (
        retirado_en IS NULL OR retirado_en >= asignado_en
    )
);
