CREATE TABLE archivo_privado (
    id_archivo NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    clave_objeto VARCHAR2(300 CHAR) NOT NULL,
    mime_type VARCHAR2(100 CHAR) NOT NULL,
    tamano_bytes NUMBER(14,0) NOT NULL,
    sha256 RAW(32) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0) NOT NULL,
    intencion_carga VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT pk_archivo_privado PRIMARY KEY (id_archivo),
    CONSTRAINT uq_archivo_clave UNIQUE (clave_objeto),
    CONSTRAINT ck_archivo_tamano CHECK (tamano_bytes > 0),
    CONSTRAINT ck_archivo_clave_opaca CHECK (
        REGEXP_LIKE(clave_objeto, '^[0-9a-f]{32}$')
    )
);

CREATE TABLE evidencia (
    id_evidencia NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_orden NUMBER(18,0) NOT NULL,
    id_archivo NUMBER(18,0) NOT NULL,
    contexto VARCHAR2(20 CHAR) NOT NULL,
    id_diagnostico NUMBER(18,0),
    id_trabajo NUMBER(18,0),
    id_presupuesto NUMBER(18,0),
    id_evaluacion NUMBER(18,0),
    visibilidad VARCHAR2(16 CHAR) NOT NULL,
    descripcion VARCHAR2(1000 CHAR) NOT NULL,
    id_evidencia_sustituida NUMBER(18,0),
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_por NUMBER(18,0) NOT NULL,
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_evidencia PRIMARY KEY (id_evidencia),
    CONSTRAINT uq_evidencia_sustituida UNIQUE (id_evidencia_sustituida),
    CONSTRAINT uq_evidencia_contexto UNIQUE (
        id_evidencia, id_orden, contexto, visibilidad
    ),
    CONSTRAINT ck_evidencia_contexto CHECK (
        contexto IN (
            'RECEPCION', 'DIAGNOSTICO', 'TRABAJO',
            'AMPLIACION', 'GARANTIA', 'ENTREGA'
        )
    ),
    CONSTRAINT ck_evidencia_visibilidad CHECK (
        visibilidad IN ('CLIENTE_ATENCION', 'INTERNA')
    ),
    CONSTRAINT ck_evidencia_variante CHECK (
        (contexto IN ('RECEPCION', 'ENTREGA')
            AND id_diagnostico IS NULL AND id_trabajo IS NULL
            AND id_presupuesto IS NULL AND id_evaluacion IS NULL)
        OR
        (contexto = 'DIAGNOSTICO'
            AND id_diagnostico IS NOT NULL AND id_trabajo IS NULL
            AND id_presupuesto IS NULL AND id_evaluacion IS NULL)
        OR
        (contexto = 'TRABAJO'
            AND id_diagnostico IS NULL AND id_trabajo IS NOT NULL
            AND id_presupuesto IS NULL AND id_evaluacion IS NULL)
        OR
        (contexto = 'AMPLIACION'
            AND id_diagnostico IS NULL AND id_trabajo IS NULL
            AND id_presupuesto IS NOT NULL AND id_evaluacion IS NULL)
        OR
        (contexto = 'GARANTIA'
            AND id_diagnostico IS NULL AND id_trabajo IS NULL
            AND id_presupuesto IS NULL AND id_evaluacion IS NOT NULL)
    ),
    CONSTRAINT ck_evidencia_recepcion_visible CHECK (
        contexto <> 'RECEPCION' OR visibilidad = 'CLIENTE_ATENCION'
    ),
    CONSTRAINT ck_evidencia_sustitucion CHECK (
        id_evidencia_sustituida IS NULL
        OR id_evidencia_sustituida <> id_evidencia
    )
);
