-- TT-024: only the technical work and diagnostic subset. The commercial item
-- relationship is added with the budget migration; no nullable generic ID is
-- stored in its place. The free path has no item or charge.
CREATE TABLE trabajo (
    id_trabajo NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_orden NUMBER(18,0) NOT NULL,
    tipo VARCHAR2(15 CHAR) NOT NULL,
    tipo_servicio VARCHAR2(60 CHAR) NOT NULL,
    descripcion VARCHAR2(1500 CHAR) NOT NULL,
    estado VARCHAR2(20 CHAR) NOT NULL,
    gratuito NUMBER(1,0) NOT NULL,
    creado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creado_por NUMBER(18,0) NOT NULL,
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_por NUMBER(18,0) NOT NULL,
    version_fila NUMBER(10,0) NOT NULL,
    CONSTRAINT pk_trabajo PRIMARY KEY (id_trabajo),
    CONSTRAINT uq_trabajo_orden UNIQUE (id_trabajo, id_orden),
    CONSTRAINT fk_trabajo_orden FOREIGN KEY (id_orden) REFERENCES orden_trabajo (id_orden),
    CONSTRAINT fk_trabajo_creador FOREIGN KEY (creado_por) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_trabajo_actualizador FOREIGN KEY (actualizado_por) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_trabajo_tipo CHECK (tipo IN ('DIAGNOSTICO', 'REPARACION')),
    CONSTRAINT ck_trabajo_estado CHECK (estado IN ('PROPUESTO','EN_EJECUCION','COMPLETADO','DETENIDO','DESCARTADO')),
    CONSTRAINT ck_trabajo_gratis CHECK (gratuito IN (0,1) AND (tipo = 'DIAGNOSTICO' OR gratuito = 0)),
    CONSTRAINT ck_trabajo_version CHECK (version_fila > 0),
    CONSTRAINT ck_trabajo_descripcion CHECK (LENGTH(TRIM(descripcion)) > 0),
    CONSTRAINT ck_trabajo_fechas CHECK (actualizado_en >= creado_en)
);

CREATE TABLE trabajo_evento (
    id_evento_trabajo NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_trabajo NUMBER(18,0) NOT NULL,
    id_mecanico NUMBER(18,0) NOT NULL,
    tipo VARCHAR2(15 CHAR) NOT NULL,
    ocurrido_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    horas_aportadas NUMBER(10,2),
    costo_interno NUMBER(14,2) NOT NULL,
    resultado_tecnico VARCHAR2(2000 CHAR),
    id_evento_origen NUMBER(18,0),
    motivo VARCHAR2(1000 CHAR) NOT NULL,
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_por NUMBER(18,0) NOT NULL,
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_trabajo_evento PRIMARY KEY (id_evento_trabajo),
    CONSTRAINT fk_trabajo_evento_trabajo FOREIGN KEY (id_trabajo) REFERENCES trabajo (id_trabajo),
    CONSTRAINT fk_trabajo_evento_mecanico FOREIGN KEY (id_mecanico) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_trabajo_evento_origen FOREIGN KEY (id_evento_origen) REFERENCES trabajo_evento (id_evento_trabajo),
    CONSTRAINT fk_trabajo_evento_actor FOREIGN KEY (registrado_por) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_trabajo_evento_comando FOREIGN KEY (id_comando) REFERENCES comando (id_comando),
    CONSTRAINT uq_trabajo_evento_origen UNIQUE (id_evento_origen),
    CONSTRAINT ck_trabajo_evento_tipo CHECK (tipo IN ('INICIO','AVANCE','FINALIZACION','DETENCION','DESCARTE','REVERSO')),
    CONSTRAINT ck_trabajo_evento_horas CHECK (horas_aportadas IS NULL OR horas_aportadas >= 0),
    CONSTRAINT ck_trabajo_evento_costo CHECK (costo_interno >= 0),
    CONSTRAINT ck_trabajo_evento_motivo CHECK (LENGTH(TRIM(motivo)) > 0)
);

CREATE TABLE diagnostico (
    id_diagnostico NUMBER(18,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_orden NUMBER(18,0) NOT NULL,
    id_trabajo_diagnostico NUMBER(18,0) NOT NULL,
    numero_revision NUMBER(5,0) NOT NULL,
    id_revision_anterior NUMBER(18,0),
    detalle_tecnico CLOB NOT NULL,
    resumen_cliente VARCHAR2(2000 CHAR) NOT NULL,
    confirmado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    registrado_por NUMBER(18,0) NOT NULL,
    id_comando NUMBER(18,0) NOT NULL,
    CONSTRAINT pk_diagnostico PRIMARY KEY (id_diagnostico),
    CONSTRAINT uq_diagnostico_revision UNIQUE (id_orden, numero_revision),
    CONSTRAINT uq_diagnostico_orden UNIQUE (id_diagnostico, id_orden),
    CONSTRAINT uq_diagnostico_anterior UNIQUE (id_revision_anterior),
    CONSTRAINT fk_diagnostico_orden FOREIGN KEY (id_orden) REFERENCES orden_trabajo (id_orden),
    CONSTRAINT fk_diagnostico_trabajo FOREIGN KEY (id_trabajo_diagnostico, id_orden) REFERENCES trabajo (id_trabajo, id_orden),
    CONSTRAINT fk_diagnostico_anterior FOREIGN KEY (id_revision_anterior, id_orden) REFERENCES diagnostico (id_diagnostico, id_orden),
    CONSTRAINT fk_diagnostico_actor FOREIGN KEY (registrado_por) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_diagnostico_comando FOREIGN KEY (id_comando) REFERENCES comando (id_comando),
    CONSTRAINT ck_diagnostico_revision CHECK (numero_revision > 0),
    CONSTRAINT ck_diagnostico_resumen CHECK (LENGTH(TRIM(resumen_cliente)) > 0)
);

CREATE INDEX ix_trabajo_orden_estado ON trabajo (id_orden, estado, id_trabajo);
CREATE INDEX ix_trabajo_evento_historia ON trabajo_evento (id_trabajo, registrado_en, id_evento_trabajo);
CREATE INDEX ix_diagnostico_trabajo ON diagnostico (id_trabajo_diagnostico, confirmado_en);
